### PR TITLE
Set neutron osp 17 as non-voting

### PR DESCRIPTION
**Pull request by bregman-arie**
Until rhbz#2069099 is resolved.

### CODE REVIEW

**Comment by karelyatin** [comment]
The bz is now resolved https://bugzilla.redhat.com/show_bug.cgi?id=2069099#c4, so can now consider revert of the workaround.

**Comment by sdatko** [comment]
> The bz is now resolved https://bugzilla.redhat.com/show_bug.cgi?id=2069099#c4, so can now consider revert of the workaround.

Hey Yatin,

I just checkend and indeed the unit test jobs succeed, however there is some problem reported by bandit in pep8 job:
```
2022-04-11 17:01:59.659623 \| container \| pep8 run-test: commands[8] \| bandit -r neutron -x tests -n5 -s B104,B303,B311,B604
--
1517 | 2022-04-11 17:01:59.659819 \| container \| setting PATH=/root/src/code.engineering.redhat.com/neutron/.tox/lint/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
1518 | 2022-04-11 17:01:59.672613 \| container \| [1652] /root/src/code.engineering.redhat.com/neutron$ /root/src/code.engineering.redhat.com/neutron/.tox/lint/bin/bandit -r neutron -x tests -n5 -s B104,B303,B311,B604
1519 | 2022-04-11 17:02:00.074385 \| container \| [main]	INFO	profile include tests: None
1520 | 2022-04-11 17:02:00.074431 \| container \| [main]	INFO	profile exclude tests: None
1521 | 2022-04-11 17:02:00.074439 \| container \| [main]	INFO	cli include tests: None
1522 | 2022-04-11 17:02:00.074457 \| container \| [main]	INFO	cli exclude tests: B104,B303,B311,B604
1523 | 2022-04-11 17:02:00.074900 \| container \| [main]	INFO	running on Python 3.9.10
1524 | 2022-04-11 17:02:22.768133 \| container \| 1039 [0.. 50.. 100.. 150.. 200.. 250.. 300.. 350.. 400.. 450.. 500.. 550.. 600.. 650.. 700.. 750.. 800.. 850.. 900.. 950.. 1000.. ]
1525 | 2022-04-11 17:02:22.773763 \| container \| Run started:2022-04-11 17:02:22.773106
1526 | 2022-04-11 17:02:22.773818 \| container \|
1527 | 2022-04-11 17:02:22.773826 \| container \| Test results:
1528 | 2022-04-11 17:02:22.773833 \| container \| >> Issue: [B324:hashlib] Use of weak MD4, MD5, or SHA1 hash for security. Consider usedforsecurity=False
1529 | 2022-04-11 17:02:22.773840 \| container \|    Severity: High   Confidence: High
1530 | 2022-04-11 17:02:22.773846 \| container \|    CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
1531 | 2022-04-11 17:02:22.773852 \| container \|    Location: neutron/plugins/ml2/drivers/openvswitch/agent/ovs_neutron_agent.py:2314:23
1532 | 2022-04-11 17:02:22.773858 \| container \|    More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b324_hashlib.html
1533 | 2022-04-11 17:02:22.773864 \| container \| 2312	            else:
1534 | 2022-04-11 17:02:22.773870 \| container \| 2313	                # Create 32-bit Base32 encoded hash
1535 | 2022-04-11 17:02:22.773875 \| container \| 2314	                sha1 = hashlib.sha1(ip_address.encode())
1536 | 2022-04-11 17:02:22.773881 \| container \| 2315	                iphash = base64.b32encode(sha1.digest())
1537 | 2022-04-11 17:02:22.773887 \| container \| 2316	                return iphash[:hashlen].decode().lower()
1538 | 2022-04-11 17:02:22.773892 \| container \|
1539 | 2022-04-11 17:02:22.773897 \| container \| --------------------------------------------------
1540 | 2022-04-11 17:02:22.773903 \| container \|
1541 | 2022-04-11 17:02:22.773909 \| container \| Code scanned:
1542 | 2022-04-11 17:02:22.773914 \| container \| 	Total lines of code: 104420
1543 | 2022-04-11 17:02:22.773920 \| container \| 	Total lines skipped (#nosec): 3
1544 | 2022-04-11 17:02:22.773925 \| container \| 	Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0
1545 | 2022-04-11 17:02:22.773931 \| container \|
1546 | 2022-04-11 17:02:22.773936 \| container \| Run metrics:
1547 | 2022-04-11 17:02:22.773941 \| container \| 	Total issues (by severity):
1548 | 2022-04-11 17:02:22.773947 \| container \| 		Undefined: 0
1549 | 2022-04-11 17:02:22.773953 \| container \| 		Low: 0
1550 | 2022-04-11 17:02:22.773958 \| container \| 		Medium: 0
1551 | 2022-04-11 17:02:22.773964 \| container \| 		High: 1
1552 | 2022-04-11 17:02:22.773970 \| container \| 	Total issues (by confidence):
1553 | 2022-04-11 17:02:22.773975 \| container \| 		Undefined: 0
1554 | 2022-04-11 17:02:22.773981 \| container \| 		Low: 0
1555 | 2022-04-11 17:02:22.773986 \| container \| 		Medium: 0
1556 | 2022-04-11 17:02:22.773991 \| container \| 		High: 1
1557 | 2022-04-11 17:02:22.773997 \| container \| Files skipped (0):
1558 | 2022-04-11 17:02:22.871664 \| container \| ERROR: InvocationError for command /root/src/code.engineering.redhat.com/neutron/.tox/lint/bin/bandit -r neutron -x tests -n5 -s B104,B303,B311,B604 (exited with code 1)
1559 | 2022-04-11 17:02:22.871713 \| container \| pep8 finish: run-test  after 379.17 seconds
1560 | 2022-04-11 17:02:22.872061 \| container \| pep8 start: run-test-post
1561 | 2022-04-11 17:02:22.872081 \| container \| pep8 finish: run-test-post  after 0.00 seconds
1562 | 2022-04-11 17:02:22.872270 \| container \| ___________________________________ summary ____________________________________
1563 | 2022-04-11 17:02:22.872287 \| container \| ERROR:   pep8: commands failed
```

Yours, Szymon

**Comment by karelyatin** [comment]
@sdatko So bandit one is a different issue, i will report seperate bz for it and propose a fix.

**Comment by karelyatin** [comment]
Reported https://bugzilla.redhat.com/show_bug.cgi?id=2074383 and pushed https://review.opendev.org/c/openstack/neutron/+/837462, if it get's accepted will backport till wallaby.

**Comment by karelyatin** [comment]
pep8 jobs also clear now after the backport https://bugzilla.redhat.com/show_bug.cgi?id=2074383, test patch https://code.engineering.redhat.com/gerrit/c/neutron/+/401401

**Comment by sdatko** [comment]
Nice, this is great news @karelyatin, thanks for taking care of this. I will make the jobs voting today.

**Pull request merged**
