### PR TITLE
Improvements for tests runs

### PR DESCRIPTION
**Pull request by sdatko**
- Reorganize tests

This commit moves existing unit tests under the znoyder/ directory,
so it is possible to run only specific test case or a single test,
which is very useful during debugging.

Example: tox -e unit -- znoyder.tests.module.TestCase.test_method

Additionally the tox environment were reorganized a little and
the yamllint environment was introduced to ensure the sanity
of Znoyder config map file. Similarly the doctests environment
was introduced to find and verify and compatible docstring.
 
- Disable logging messages in unit tests

This commit quiets up the logging messages in unit tests.
Right now its output interferes with the tests logs.
The produced logging messages however are not really
useful in the unit testing output, so I disable them.

Additionally I suppress the help messages form argparse
module for the same reason in CLI tests.

Last I disable printing of the tests docstrings
as unittest module outputs them and while they may
explain goal of each test to developer, in the tox
output it would be cleaner to have just function names.

### CODE REVIEW

**Comment by jsanemet** [comment]
If you want to do it in one go, you can patch '_print_message' for all tests in one go with something like:
```python
...
def setUp(self):
    self.mock_argpare_print = patch('argparse.ArgumentParser._print_message')
...
```
Just a comment, everything seems fine.

**Review by jsanemet — APPROVED** [review]

**Review by IgnacioPro — APPROVED** [review]
LGTM!

**Review by cescgina — APPROVED** [review]
+1 silencing the tests output is a great improvement

**Review by adrianfusco — APPROVED** [review]
Good changes!

**Comment by sdatko** [comment]
> If you want to do it in one go, you can patch '_print_message' for all tests with something like:
> 
> ```python
> ...
> def setUp(self):
>     self.mock_argpare_print = patch('argparse.ArgumentParser._print_message')
> ...
> ```
> 
> Just a comment, everything else seems fine.

Good to know, it may be useful in the future, thanks!

**Pull request merged**
